version: "3.5"

services:
  esdb-node1:
    image: eventstore/eventstore
    env_file:
      - shared.env
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=127.0.0.1
      - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2111
      - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1111
    ports:
      - 1113:1113
      - 2113:2113
    restart: unless-stopped
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  client:
    build: ./
    volumes:
      - ./:/usr/src/poc
    depends_on:
      - redis
      - esdb-node1
      - mongo
    ports:
      - 8001:8001
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
